apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260508-190209-zak0ezcud25n-service
spec:
  selector:
    app: enterprise-system-20260508-190209-zak0ezcud25n
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
